from ast import keyword
from keyword import kwlist


print('a'.isidentifier())
print('A'.isidentifier())
print('_'.isidentifier())
print('3_4'.isidentifier())
print('if'.isidentifier())

import keyword as kk
print(kk.kwlist)
print(len(kk.kwlist))
print(kk.iskeyword('nonlocal'))
print(kk.iskeyword('try'))
print(kk.iskeyword('while'))
print(kk.iskeyword('continue'))
print(kk.iskeyword('not'))
print(kk.iskeyword('yeild'))
print(kk.iskeyword('def'))
print(kk.iskeyword('del'))
print(kk.iskeyword('defn'))
print(kk.iskeyword('except'))
print(kk.iskeyword('class'))
print(kk.iskeyword('lambda'))
print(kk.iskeyword('pass'))
print(kk.iskeyword('return'))
print(kk.iskeyword('or'))
print(kk.iskeyword('global'))
print(kk.iskeyword('def'))
print(kk.iskeyword('from'))
print(kk.iskeyword('in'))
print(kk.iskeyword('for'))
print(kk.iskeyword('if'))
print(kk.iskeyword('is'))
print(kk.iskeyword('not'))
